import type { Message, Draft, Brief } from "@/types";

export const MOCK_USER = {
  name: "Marcus Chen",
  email: "marcus.chen@northstar.io",
  initials: "MC",
};

export const MOCK_MESSAGES: Message[] = [
  {
    id: "msg-1",
    gmailMessageId: "gm-1",
    gmailThreadId: "gt-1",
    subject: "Q3 budget approval needed by EOD",
    senderEmail: "sarah.kim@northstar.io",
    senderName: "Sarah Kim",
    receivedAt: new Date(Date.now() - 12 * 60 * 1000).toISOString(),
    bodyPreview: "Marcus, the finance committee needs your sign-off on the Q3 budget before 5 PM today. The revised figures are attached.",
    hasDraft: false,
    triage: {
      id: "tr-1",
      priority: "urgent",
      confidence: 0.93,
      rationale: "Budget approval with an EOD deadline from your CFO requires immediate action.",
      labels: ["finance", "action-required"],
      modelVersion: "gpt-4o-2024-11",
      createdAt: new Date(Date.now() - 11 * 60 * 1000).toISOString(),
    },
    workflowState: "triaged",
  },
  {
    id: "msg-2",
    gmailMessageId: "gm-2",
    gmailThreadId: "gt-2",
    subject: "Investor deck feedback — round 2",
    senderEmail: "alex.park@sequoia.com",
    senderName: "Alex Park",
    receivedAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    bodyPreview: "Thanks for the updated deck. We have a few questions before the Thursday call. See inline comments on slides 8 and 12.",
    hasDraft: true,
    triage: {
      id: "tr-2",
      priority: "urgent",
      confidence: 0.88,
      rationale: "Investor communication with Thursday deadline and inline questions needing a response.",
      labels: ["investor-relations", "reply-needed"],
      modelVersion: "gpt-4o-2024-11",
      createdAt: new Date(Date.now() - 44 * 60 * 1000).toISOString(),
    },
    workflowState: "draft_queued",
  },
  {
    id: "msg-3",
    gmailMessageId: "gm-3",
    gmailThreadId: "gt-3",
    subject: "Re: Product roadmap sync",
    senderEmail: "priya.r@northstar.io",
    senderName: "Priya Raghavan",
    receivedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    bodyPreview: "Sounds good — I'll prepare the prioritization matrix before our Friday session. Should I loop in design?",
    hasDraft: false,
    triage: {
      id: "tr-3",
      priority: "normal",
      confidence: 0.76,
      rationale: "Scheduling coordination from a direct report. Needs a yes/no reply.",
      labels: ["team", "reply-needed"],
      modelVersion: "gpt-4o-2024-11",
      createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000 + 30000).toISOString(),
    },
    workflowState: "triaged",
  },
  {
    id: "msg-4",
    gmailMessageId: "gm-4",
    gmailThreadId: "gt-4",
    subject: "Newsletter: SaaS benchmarks — May 2025",
    senderEmail: "insights@saasmetrics.co",
    senderName: "SaaS Metrics",
    receivedAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    bodyPreview: "Your monthly benchmarks are ready. ARR growth median for Series A companies: 2.4× YoY. NRR top quartile: 118%.",
    hasDraft: false,
    triage: {
      id: "tr-4",
      priority: "brief",
      confidence: 0.97,
      rationale: "Newsletter from a subscribed service — no reply needed, good for the brief.",
      labels: ["newsletter", "industry"],
      modelVersion: "gpt-4o-2024-11",
      createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000 + 30000).toISOString(),
    },
    workflowState: "brief_queued",
  },
];

export const MOCK_DRAFTS: Draft[] = [
  {
    id: "draft-1",
    workflowRunId: "run-1",
    body: "Hi Alex,\n\nThank you for the detailed feedback on slides 8 and 12. I've reviewed your comments and wanted to address each point:\n\nSlide 8 (Go-to-market timeline): You're right that Q3 looks ambitious. We've adjusted the assumptions to reflect a 6-week pilot phase before full rollout. The revised slide will be in your inbox by tomorrow morning.\n\nSlide 12 (Unit economics): The CAC payback period currently assumes 18 months based on our enterprise cohort. Happy to walk through the SMB cohort separately on Thursday if that would be helpful.\n\nLooking forward to the call.\n\nBest,\nMarcus",
    subjectLine: "Re: Investor deck feedback — round 2",
    confidence: 0.84,
    status: "pending",
    userFeedback: "Reply to investor slide feedback covering two specific questions about GTM timeline and unit economics.",
    createdAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    reviewedAt: null,
    originalMessage: MOCK_MESSAGES[1],
  },
  {
    id: "draft-2",
    workflowRunId: "run-2",
    body: "Hi Priya,\n\nYes, please loop in design — their input on the prioritization matrix will be valuable, especially for the new onboarding flow items.\n\nSee you Friday!\n\nMarcus",
    subjectLine: "Re: Product roadmap sync",
    confidence: 0.91,
    status: "pending",
    userFeedback: "Short affirmative reply to a scheduling question from a direct report.",
    createdAt: new Date(Date.now() - 90 * 60 * 1000).toISOString(),
    reviewedAt: null,
    originalMessage: MOCK_MESSAGES[2],
  },
];

export const MOCK_BRIEF: Brief = {
  id: "brief-1",
  timeWindow: "morning",
  summaryMarkdown: "You have 2 urgent items requiring action today: the Q3 budget approval (EOD deadline from Sarah) and the investor deck follow-up for Alex Park's Thursday call. Priya is ready for Friday's roadmap sync and just needs a quick yes/no on design involvement. The SaaS benchmarks newsletter has been filed to your brief for context.",
  actionItems: [
    { text: "Approve Q3 budget and send to finance committee", from: "Sarah Kim", due: "Today", messageId: "msg-1" },
    { text: "Review slides 8 & 12 and send revised deck to Alex", from: "Alex Park", due: "Wednesday", messageId: "msg-2" },
    { text: "Confirm design involvement for roadmap sync", from: "Priya Raghavan", due: "Friday", messageId: "msg-3" },
  ],
  messageIds: ["msg-1", "msg-2", "msg-3", "msg-4"],
  createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
  threadCount: 4,
  generatedAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
  modelVersion: "gpt-4o-2024-11",
};
